[package]
name = "hidden-words-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"  # For image loading
regex = "1.5"  # Optional for word list extraction
